CREATE TABLE IF NOT EXISTS ENCARGADO (
    RUT VARCHAR(10),
    NOMBRE VARCHAR(40),
    PRIMARY KEY (RUT)
)

CREATE TABLE IF NOT EXISTS UBICACION (
    ID SERIAL,
    NOMBRE VARCHAR(40),
    PRIMARY KEY (ID)
)

CREATE TABLE IF NOT EXISTS RUBRO (
    ID SERIAL,
    NOMBRE VARCHAR(40),
    PRIMARY KEY (ID)
)

CREATE TABLE IF NOT EXISTS ESPECIE (
    ID SERIAL,
    NOMBRE VARCHAR(40),
    PRIMARY KEY (ID)
)

CREATE TABLE IF NOT EXISTS PRODUCTO (
    ID SERIAL,
    DESCRIPCION VARCHAR(50) NOT NULL,
    PRECIO INT NOT NULL,
    FECHA BIGINT NOT NULL,
    RUT_ENCARGADO VARCHAR(10) NOT NULL,
    ID_UBICACION BIGINT UNSIGNED NOT NULL,
    ID_RUBRO BIGINT UNSIGNED NOT NULL,
    ID_ESPECIE BIGINT UNSIGNED NOT NULL,
    OBSERVACION VARCHAR(100),
    
    PRIMARY KEY (ID),
    FOREIGN KEY (FOLIO) REFERENCES FACTURA(FOLIO) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (RUT_ENCARGADO) REFERENCES ENCARGADO(RUT) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ID_UBICACION) REFERENCES UBICACION(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ID_RUBRO) REFERENCES RUBRO(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ID_ESPECIE) REFERENCES ESPECIE(ID) ON UPDATE CASCADE ON DELETE CASCADE
)



